name: Build SM-T295 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git bc bison flex \
            build-essential \
            libssl-dev \
            libelf-dev \
            python3

      - name: Clone Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Configure Kernel
        run: |
          export ARCH=arm64
          make O=out lineageos_gtowifi_defconfig

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH=$PWD/clang/bin:$PATH

          make O=out -j$(nproc) \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SM-T295-Kernel
          path: |
            out/arch/arm64/boot/Image*
            out/arch/arm64/boot/dts/
